mysql:
  host: 127.0.0.1
  username: root
  password: root
  port: 3306
  database: blog
site:
  pageSize: 10
  address: :8000
  remember_days: 30
  domain: blog.iwww.me
  uploadPath: /Users/wangweiwei/Downloads/uploads
session:
  maxAge: 3600
recaptcha:
  secret: xxx
  score: 0.9
appKey: T1SDu7fxVR6PogZ1TCr8Ou8FlCWGYvWD
